obj-$(CONFIG_TOUCHSCREEN_FTS_1695) += focaltech_upgrade_ft5446dqs_xxx.o
# HS60 code for HS60-5982 by zhawei at 2023/11/10 start
obj-$(CONFIG_TOUCHSCREEN_FTS_1695) += focaltech_upgrade_ft5446u.o
# HS60 code for HS60-5982 by zhawei at 2023/11/10 end
